version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.3-debian
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 3001:3001
    restart: always
