version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: 'nginx-proxy-manager'
    restart: unless-stopped
    ports:
      - '80:80'
      - '127.0.0.1:81:81'
      - '443:443'
    extra_hosts:
    - "host.docker.internal:host-gateway"

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

    networks:
      - proxy-localhost
      - nextcloud-aio

networks:
  proxy-localhost:
    external: true
    name: proxy-localhost
  nextcloud-aio:
    external: true
    name: nextcloud-aio
